printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
trailingComma: all

overrides:
- files: "*.css"
  options:
    parser: css
    singleQuote: false
- files: "*.json"
  options:
    singleQuote: false
- files: "*.vue"
  options:
    parser: vue
